export const GET_ALL = 'GET_ALL';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER = 'REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';

export const LOAD_USER = 'LOAD_USER';
export const USER_LOADED = 'USER_LOADED';

export const GET_EVENTLOGS = 'GET_EVENTLOGS';
export const ADD_EVENTLOG = 'ADD_EVENTLOG';
export const REMOVE_EVENTLOG = 'REMOVE_EVENTLOG';
export const EVENTLOGS_LOADED = 'EVENTLOGS_LOADED';
export const EVENTLOG_ERROR = 'EVENTLOG_ERROR';

export const GET_FILTERS = 'GET_FILTERS';
export const ADD_FILTER = 'ADD_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
export const FILTERS_LOADED = 'FILTERS_LOADED';
export const FILTER_ERROR = 'FILTER_ERROR';

export const STARTRECORD_EVENTLOG = 'STARTRECORD_EVENTLOG';
export const STOPRECORD_EVENTLOG = 'STOPRECORD_EVENTLOG';

export const STARTPLAYBACK_EVENTLOG = 'STARTPLAYBACK_EVENTLOG';
export const STOPPLAYBACK_EVENTLOG = 'STOPPLAYBACK_EVENTLOG';

export const EVENTLOG_UPDATED = 'EVENTLOG_UPDATED';
export const EVENTLOG_ADDED = 'EVENTLOG_ADDED';
export const EVENTLOG_REMOVED = 'EVENTLOG_REMOVED';

export const FILTER_UPDATED = 'FILTER_UPDATED';
export const FILTER_ADDED = 'FILTER_ADDED';
export const FILTER_REMOVED = 'FILTER_REMOVED';

export const GET_JOBS = 'GET_JOBS';
export const JOBS_LOADED = 'JOBS_LOADED';
export const JOB_ADDED = 'JOB_ADDED';
export const JOB_REMOVED = 'JOB_REMOVED';
export const JOB_UPDATED = 'JOB_UPDATED';
export const JOB_ERROR = 'JOB_ERROR';

export const AUTH_ERROR = 'AUTH_ERROR';
